apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-code-education
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-code-education
  template:
    metadata:
      labels:
        app: nginx-code-education
    spec:
      containers:
        - name: nginx
          image: deividj80/nginx-code-education
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
